# Generated by Django 2.0.10 on 2019-02-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_data', models.DateTimeField(auto_now_add=True)),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissao.Clientes')),
                ('pedido_itens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emissao.Itens')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto_nome', models.CharField(max_length=50)),
                ('produto_preco', models.CharField(max_length=50)),
                ('produto_multiplo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itens',
            name='item_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissao.Produtos'),
        ),
    ]
