# Generated by Django 2.0.10 on 2019-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto_nome', models.CharField(max_length=50)),
                ('produto_preco', models.CharField(max_length=50)),
                ('produto_multiplo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
