# Generated by Django 2.0.10 on 2019-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='item_preco_escolhido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
