# Generated by Django 2.0.10 on 2019-02-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissao', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_data', models.DateTimeField(auto_now_add=True)),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissao.Clientes')),
                ('pedido_produto', models.ManyToManyField(to='emissao.Produtos')),
            ],
        ),
    ]
