# Generated by Django 2.0.10 on 2019-02-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissao', '0002_itens_item_preco_escolhido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido_itens',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_itens',
            field=models.ManyToManyField(null=True, to='emissao.Itens'),
        ),
    ]
