# Generated by Django 2.0.10 on 2019-02-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissao', '0003_auto_20190212_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_itens',
            field=models.ManyToManyField(to='emissao.Itens'),
        ),
    ]
